[workspace]
members = [
    "crates/*", "lib/aws",
]
resolver = "2"

[workspace.package]
rust-version = "1.76"
edition = "2021"
license = "GPL v3.0"
authors = [
    "Amanami team",
]

[profile.dev]
debug = 0

[profile.release]
debug = 0

[workspace.dependencies]
colored = "2"
